name: Unit Tests

on: [ push, pull_request ]

jobs:
  unit-tests:
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: Checkout Branch
        uses: actions/checkout@v2

      - id: install-dashboards
        uses: ./.github/actions/install-dashboards
        with:
           plugin_name: security-dashboards-plugin

      - name: Run lint
        run: yarn lint
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Run unit test
        run: yarn test:jest_ui --coverage
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Uploads coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
